project:
  type: website

website:
  title: "Data Skills Portfolio Program"
  sidebar: 
    style: "docked"
    search: true
    contents: 
    - title: "What is the DSP Program?"
      href: intro.qmd
      contents:
        - philosophy.qmd
        - structure.qmd
    - title: "The DSP Program Handbook"
      href: handbookIntro.qmd
      section: "Data Curation"
      href: handbookDCIntro.qmd
      section: "Data Analysis"
      href: handbookDAIntro.qmd
      section: "Statistical Modelling"
      href: handbookSMIntro.qmd
      section: "FAQs"
      href: FAQ.qmd
    - title: "Feedback"
      href: feedback.qmd
    

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



