project:
  type: website

website:
  title: "Data Skills Portfolio Program"
  sidebar: 
    style: "docked"
    search: true
    contents: 
    - section: "What is the DSP Program?"
      href: intro.qmd
      contents:
        - philosophy.qmd
        - structure.qmd
    - section: "The DSP Program Handbook"
      href: handbookIntro.qmd
      contents: 
        - handbookDCIntro.qmd
        - handbookDAIntro.qmd
        - handbookSMIntro.qmd
        - FAQ.qmd
    - section: "Feedback"
      href: feedback.qmd
    

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



