project:
  type: website

website:
  title: "DSPProgram.AUBiology.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - handbookIntro.qmd
      - intro.qmd
      - structure.qmd
      - feedback.qmd
      - FAQ.qmd
      - philosophy.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



