project:
  type: website

website:
  title: "Data Skills Portfolio Program"
  navbar: 
    background: primary
    search: true
    left: 
      - text: "Home"
        href: index.qmd
      - text: "What is the DSP Program?"
        href: intro.qmd
      - text: "The DSP Program Handbook"
        href: handbookIntro.qmd
      - text: "Feedback"
        href: feedback.qmd
        
  sidebar:
    - title: "What is the DSP Program?"
      style: "docked"
      background: light
      contents:
        - intro.qmd
        - philosophy.qmd
        - structure.qmd
        
    - title: "The DSP Program Handbook"
      contents: 
        - handbookIntro.qmd
        - handbookDCIntro.qmd
        #- handbookDAIntro.qmd
        #- handbookSMIntro.qmd
        - FAQ.qmd
    

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



